name: Deploy to Staging
on:
  push:
    branches: [develop]
jobs:
  deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_ACADEMIC_ALLIES_464901 }}
          channelId: live
          projectId: academic-allies-464901
          target: staging
